version: '3.1'

services:
 postgres:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    volumes:
      - /data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tweets
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user